// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/learning/grammar/messages/{messageId}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Analyze a message transcript for grammar and naturalness, save the result",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "learning"
                ],
                "summary": "Analyze grammar for a message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Message ID",
                        "name": "messageId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Language for the explanation (e.g. vietnamese)",
                        "name": "explanationLanguage",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-github_com_gianghp123_SonaVoice_api_internal_modules_learning_dtos_res_GrammarAIResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/sessions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get paginated list of sessions belonging to the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "List user sessions",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default 10, max 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-array_github_com_gianghp123_SonaVoice_api_internal_modules_session_dtos_res_SessionListItemRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new session and start a WebRTC connection with the speech service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Create new session and start connection",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-github_com_gianghp123_SonaVoice_api_internal_modules_session_dtos_res_CreateSessionRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/sessions/config": {
            "get": {
                "description": "Retrieve the session configuration",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session-config"
                ],
                "summary": "Get session config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-github_com_gianghp123_SonaVoice_api_internal_modules_session_dtos_res_SessionConfigRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update the session configuration (admin only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session-config"
                ],
                "summary": "Update session config",
                "parameters": [
                    {
                        "description": "Session config payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_modules_session_dtos_req.SessionConfigReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-github_com_gianghp123_SonaVoice_api_internal_modules_session_dtos_res_SessionConfigRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/sessions/{sessionId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a single session by ID (must belong to the authenticated user)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Get session details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-github_com_gianghp123_SonaVoice_api_internal_modules_session_dtos_res_SessionRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/sessions/{sessionId}/api/offer": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Proxy a WebRTC offer request to the speech service by session ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Proxy WebRTC offer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "WebRTC offer request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {}
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Proxy a WebRTC offer request to the speech service by session ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Proxy WebRTC offer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "WebRTC offer request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {}
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/sessions/{sessionId}/cancel": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cancel a pending or active session, releasing all reserved quota",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Cancel a session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/sessions/{sessionId}/messages": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get paginated list of messages for a session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "message"
                ],
                "summary": "List messages in a session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default 10, max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order (asc/desc)",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-array_github_com_gianghp123_SonaVoice_api_internal_modules_message_dtos_res_MessageRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    }
                }
            },
            "post": {
                "description": "Create new messages for a session (internal endpoint)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "message"
                ],
                "summary": "Create messages in a session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Messages to create",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_modules_message_dtos_req.CreateMessagesReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-array_github_com_gianghp123_SonaVoice_api_internal_modules_message_dtos_res_MessageRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/sessions/{sessionId}/start": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Start a WebRTC connection for a pending session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Start connection for an existing session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-github_com_gianghp123_SonaVoice_api_internal_modules_session_dtos_res_CreateSessionRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_gianghp123_SonaVoice_api_internal_core_enums.MessageRole": {
            "type": "string",
            "enum": [
                "user",
                "assistant"
            ],
            "x-enum-varnames": [
                "MessageRoleUser",
                "MessageRoleAssistant"
            ]
        },
        "github_com_gianghp123_SonaVoice_api_internal_core_enums.SessionStatus": {
            "type": "string",
            "enum": [
                "pending",
                "active",
                "inactive",
                "failed"
            ],
            "x-enum-varnames": [
                "SessionStatusPending",
                "SessionStatusActive",
                "SessionStatusInactive",
                "SessionStatusFailed"
            ]
        },
        "github_com_gianghp123_SonaVoice_api_internal_core_errors.AppError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-any": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_errors.AppError"
                },
                "meta": {
                    "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.Meta"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-array_github_com_gianghp123_SonaVoice_api_internal_modules_message_dtos_res_MessageRes": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_modules_message_dtos_res.MessageRes"
                    }
                },
                "error": {
                    "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_errors.AppError"
                },
                "meta": {
                    "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.Meta"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-array_github_com_gianghp123_SonaVoice_api_internal_modules_session_dtos_res_SessionListItemRes": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_modules_session_dtos_res.SessionListItemRes"
                    }
                },
                "error": {
                    "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_errors.AppError"
                },
                "meta": {
                    "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.Meta"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-github_com_gianghp123_SonaVoice_api_internal_modules_learning_dtos_res_GrammarAIResult": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_modules_learning_dtos_res.GrammarAIResult"
                },
                "error": {
                    "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_errors.AppError"
                },
                "meta": {
                    "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.Meta"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-github_com_gianghp123_SonaVoice_api_internal_modules_session_dtos_res_CreateSessionRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_modules_session_dtos_res.CreateSessionRes"
                },
                "error": {
                    "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_errors.AppError"
                },
                "meta": {
                    "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.Meta"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-github_com_gianghp123_SonaVoice_api_internal_modules_session_dtos_res_SessionConfigRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_modules_session_dtos_res.SessionConfigRes"
                },
                "error": {
                    "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_errors.AppError"
                },
                "meta": {
                    "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.Meta"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_gianghp123_SonaVoice_api_internal_core_response.BaseResponse-github_com_gianghp123_SonaVoice_api_internal_modules_session_dtos_res_SessionRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_modules_session_dtos_res.SessionRes"
                },
                "error": {
                    "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_errors.AppError"
                },
                "meta": {
                    "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_response.Meta"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_gianghp123_SonaVoice_api_internal_core_response.Meta": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "github_com_gianghp123_SonaVoice_api_internal_modules_learning_dtos_res.GrammarAIResult": {
            "type": "object",
            "properties": {
                "correctedText": {
                    "type": "string"
                },
                "explanation": {
                    "type": "string"
                },
                "hasCorrection": {
                    "type": "boolean"
                },
                "metadata": {},
                "originalText": {
                    "type": "string"
                },
                "practiceFocus": {
                    "type": "string"
                },
                "practiceReason": {
                    "type": "string"
                },
                "practiceSentence": {
                    "type": "string"
                },
                "severity": {
                    "type": "string",
                    "enum": [
                        "low",
                        "medium",
                        "high"
                    ]
                }
            }
        },
        "github_com_gianghp123_SonaVoice_api_internal_modules_message_dtos_req.CreateMessagesReq": {
            "type": "object",
            "required": [
                "messages"
            ],
            "properties": {
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_modules_message_dtos_req.MessageItem"
                    }
                }
            }
        },
        "github_com_gianghp123_SonaVoice_api_internal_modules_message_dtos_req.MessageItem": {
            "type": "object",
            "required": [
                "role"
            ],
            "properties": {
                "role": {
                    "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_enums.MessageRole"
                },
                "transcript": {
                    "type": "string"
                },
                "was_interrupted": {
                    "type": "boolean"
                }
            }
        },
        "github_com_gianghp123_SonaVoice_api_internal_modules_message_dtos_res.MessageRes": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_enums.MessageRole"
                },
                "session_id": {
                    "type": "string"
                },
                "transcript": {
                    "type": "string"
                },
                "was_interrupted": {
                    "type": "boolean"
                }
            }
        },
        "github_com_gianghp123_SonaVoice_api_internal_modules_session_dtos.ConfigPayload": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "limits": {
                    "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_modules_session_dtos.LimitsConfig"
                },
                "reset_timezone": {
                    "type": "string"
                }
            }
        },
        "github_com_gianghp123_SonaVoice_api_internal_modules_session_dtos.LimitsConfig": {
            "type": "object",
            "properties": {
                "session": {
                    "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_modules_session_dtos.SessionLimitConfig"
                },
                "user": {
                    "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_modules_session_dtos.UserLimitConfig"
                }
            }
        },
        "github_com_gianghp123_SonaVoice_api_internal_modules_session_dtos.SessionLimitConfig": {
            "type": "object",
            "properties": {
                "max_session_lockTTL": {
                    "type": "integer"
                }
            }
        },
        "github_com_gianghp123_SonaVoice_api_internal_modules_session_dtos.UserLimitConfig": {
            "type": "object",
            "properties": {
                "daily_request_count": {
                    "type": "integer"
                },
                "daily_voice_seconds": {
                    "type": "integer"
                }
            }
        },
        "github_com_gianghp123_SonaVoice_api_internal_modules_session_dtos_req.SessionConfigReq": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_modules_session_dtos.ConfigPayload"
                }
            }
        },
        "github_com_gianghp123_SonaVoice_api_internal_modules_session_dtos_res.CreateSessionRes": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "max_duration": {
                    "type": "integer"
                },
                "webrtc_connection": {
                    "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_modules_session_dtos_res.WebRTCConnectionRes"
                }
            }
        },
        "github_com_gianghp123_SonaVoice_api_internal_modules_session_dtos_res.IceConfig": {
            "type": "object",
            "properties": {
                "iceServers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_modules_session_dtos_res.IceServer"
                    }
                }
            }
        },
        "github_com_gianghp123_SonaVoice_api_internal_modules_session_dtos_res.IceServer": {
            "type": "object",
            "properties": {
                "credential": {
                    "description": "for TURN servers",
                    "type": "string"
                },
                "urls": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "username": {
                    "description": "for TURN servers",
                    "type": "string"
                }
            }
        },
        "github_com_gianghp123_SonaVoice_api_internal_modules_session_dtos_res.SessionConfigRes": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_modules_session_dtos.ConfigPayload"
                }
            }
        },
        "github_com_gianghp123_SonaVoice_api_internal_modules_session_dtos_res.SessionListItemRes": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_enums.SessionStatus"
                }
            }
        },
        "github_com_gianghp123_SonaVoice_api_internal_modules_session_dtos_res.SessionRes": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_core_enums.SessionStatus"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "github_com_gianghp123_SonaVoice_api_internal_modules_session_dtos_res.WebRTCConnectionRes": {
            "type": "object",
            "properties": {
                "iceConfig": {
                    "description": "only if enableDefaultIceServers: true",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_gianghp123_SonaVoice_api_internal_modules_session_dtos_res.IceConfig"
                        }
                    ]
                },
                "maxDuration": {
                    "type": "integer"
                },
                "sessionId": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Session API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
