// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/session-config": {
            "get": {
                "description": "Retrieve the session configuration",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session-config"
                ],
                "summary": "Get session config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-res_SessionConfigRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-any"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Update the session configuration (admin only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session-config"
                ],
                "summary": "Update session config",
                "parameters": [
                    {
                        "description": "Session config payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/req.SessionConfigReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-res_SessionConfigRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-any"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-any"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/sessions": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Create a new session and start a WebRTC connection with the speech service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Create new session and start connection",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-res_CreateSessionRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-any"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-any"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/sessions/{sessionId}/offer": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Proxy a WebRTC offer request to the speech service by session ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Proxy WebRTC offer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "WebRTC offer request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {}
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-any"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-any"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Proxy a WebRTC offer request to the speech service by session ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Proxy WebRTC offer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "WebRTC offer request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {}
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-any"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/sessions/{sessionId}/start": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Start a WebRTC connection for a pending session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Start connection for an existing session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-res_CreateSessionRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-any"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-any"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-any"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dtos.ConfigPayload": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "limits": {
                    "$ref": "#/definitions/dtos.LimitsConfig"
                },
                "reset_timezone": {
                    "type": "string"
                }
            }
        },
        "dtos.LimitsConfig": {
            "type": "object",
            "properties": {
                "session": {
                    "$ref": "#/definitions/dtos.SessionLimitConfig"
                },
                "user": {
                    "$ref": "#/definitions/dtos.UserLimitConfig"
                }
            }
        },
        "dtos.SessionLimitConfig": {
            "type": "object",
            "properties": {
                "max_session_lockTTL": {
                    "type": "integer"
                }
            }
        },
        "dtos.UserLimitConfig": {
            "type": "object",
            "properties": {
                "daily_request_count": {
                    "type": "integer"
                },
                "daily_voice_seconds": {
                    "type": "integer"
                }
            }
        },
        "errors.AppError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "req.SessionConfigReq": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/dtos.ConfigPayload"
                }
            }
        },
        "res.CreateSessionRes": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "max_duration": {
                    "type": "integer"
                },
                "webrtc_connection": {
                    "$ref": "#/definitions/res.WebRTCConnectionRes"
                }
            }
        },
        "res.IceConfig": {
            "type": "object",
            "properties": {
                "iceServers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/res.IceServer"
                    }
                }
            }
        },
        "res.IceServer": {
            "type": "object",
            "properties": {
                "credential": {
                    "description": "for TURN servers",
                    "type": "string"
                },
                "urls": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "username": {
                    "description": "for TURN servers",
                    "type": "string"
                }
            }
        },
        "res.SessionConfigRes": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/dtos.ConfigPayload"
                }
            }
        },
        "res.WebRTCConnectionRes": {
            "type": "object",
            "properties": {
                "iceConfig": {
                    "description": "only if enableDefaultIceServers: true",
                    "allOf": [
                        {
                            "$ref": "#/definitions/res.IceConfig"
                        }
                    ]
                },
                "sessionId": {
                    "type": "string"
                }
            }
        },
        "response.BaseResponse-any": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "$ref": "#/definitions/errors.AppError"
                },
                "meta": {
                    "$ref": "#/definitions/response.Meta"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.BaseResponse-res_CreateSessionRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/res.CreateSessionRes"
                },
                "error": {
                    "$ref": "#/definitions/errors.AppError"
                },
                "meta": {
                    "$ref": "#/definitions/response.Meta"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.BaseResponse-res_SessionConfigRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/res.SessionConfigRes"
                },
                "error": {
                    "$ref": "#/definitions/errors.AppError"
                },
                "meta": {
                    "$ref": "#/definitions/response.Meta"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.Meta": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Session API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
